# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcdsWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.SensorTab = QtGui.QWidget()
        self.SensorTab.setObjectName(_fromUtf8("SensorTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.SensorTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.SensorGroupBox = QtGui.QGroupBox(self.SensorTab)
        self.SensorGroupBox.setFlat(True)
        self.SensorGroupBox.setCheckable(False)
        self.SensorGroupBox.setObjectName(_fromUtf8("SensorGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.SensorGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.SerialRadioButton = QtGui.QRadioButton(self.SensorGroupBox)
        self.SerialRadioButton.setChecked(True)
        self.SerialRadioButton.setObjectName(_fromUtf8("SerialRadioButton"))
        self.verticalLayout_3.addWidget(self.SerialRadioButton)
        self.BLERadioButton = QtGui.QRadioButton(self.SensorGroupBox)
        self.BLERadioButton.setChecked(False)
        self.BLERadioButton.setObjectName(_fromUtf8("BLERadioButton"))
        self.verticalLayout_3.addWidget(self.BLERadioButton)
        self.verticalLayout_2.addWidget(self.SensorGroupBox)
        self.ScanDevicesButton = QtGui.QPushButton(self.SensorTab)
        self.ScanDevicesButton.setObjectName(_fromUtf8("ScanDevicesButton"))
        self.verticalLayout_2.addWidget(self.ScanDevicesButton)
        self.DeviceListComboBox = QtGui.QComboBox(self.SensorTab)
        self.DeviceListComboBox.setObjectName(_fromUtf8("DeviceListComboBox"))
        self.verticalLayout_2.addWidget(self.DeviceListComboBox)
        self.DeviceConnectButton = QtGui.QPushButton(self.SensorTab)
        self.DeviceConnectButton.setEnabled(False)
        self.DeviceConnectButton.setObjectName(_fromUtf8("DeviceConnectButton"))
        self.verticalLayout_2.addWidget(self.DeviceConnectButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.IDLabel = QtGui.QLabel(self.SensorTab)
        self.IDLabel.setObjectName(_fromUtf8("IDLabel"))
        self.gridLayout_6.addWidget(self.IDLabel, 0, 0, 1, 1)
        self.IDLineEdit = QtGui.QLineEdit(self.SensorTab)
        self.IDLineEdit.setObjectName(_fromUtf8("IDLineEdit"))
        self.gridLayout_6.addWidget(self.IDLineEdit, 0, 1, 1, 1)
        self.LocLabel = QtGui.QLabel(self.SensorTab)
        self.LocLabel.setObjectName(_fromUtf8("LocLabel"))
        self.gridLayout_6.addWidget(self.LocLabel, 1, 0, 1, 1)
        self.LocLineEdit = QtGui.QLineEdit(self.SensorTab)
        self.LocLineEdit.setObjectName(_fromUtf8("LocLineEdit"))
        self.gridLayout_6.addWidget(self.LocLineEdit, 1, 1, 1, 1)
        self.DirLabel = QtGui.QLabel(self.SensorTab)
        self.DirLabel.setObjectName(_fromUtf8("DirLabel"))
        self.gridLayout_6.addWidget(self.DirLabel, 2, 0, 1, 1)
        self.DirLineEdit = QtGui.QLineEdit(self.SensorTab)
        self.DirLineEdit.setObjectName(_fromUtf8("DirLineEdit"))
        self.gridLayout_6.addWidget(self.DirLineEdit, 2, 1, 1, 1)
        self.CommentLabel = QtGui.QLabel(self.SensorTab)
        self.CommentLabel.setObjectName(_fromUtf8("CommentLabel"))
        self.gridLayout_6.addWidget(self.CommentLabel, 3, 0, 1, 1)
        self.CommentLineEdit = QtGui.QLineEdit(self.SensorTab)
        self.CommentLineEdit.setObjectName(_fromUtf8("CommentLineEdit"))
        self.gridLayout_6.addWidget(self.CommentLineEdit, 3, 1, 1, 1)
        self.StateLabel = QtGui.QLabel(self.SensorTab)
        self.StateLabel.setObjectName(_fromUtf8("StateLabel"))
        self.gridLayout_6.addWidget(self.StateLabel, 4, 0, 1, 1)
        self.StateLineEdit = QtGui.QLineEdit(self.SensorTab)
        self.StateLineEdit.setReadOnly(True)
        self.StateLineEdit.setObjectName(_fromUtf8("StateLineEdit"))
        self.gridLayout_6.addWidget(self.StateLineEdit, 4, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.SetButton = QtGui.QPushButton(self.SensorTab)
        self.SetButton.setEnabled(False)
        self.SetButton.setObjectName(_fromUtf8("SetButton"))
        self.verticalLayout_5.addWidget(self.SetButton)
        self.StartButton = QtGui.QPushButton(self.SensorTab)
        self.StartButton.setEnabled(False)
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.verticalLayout_5.addWidget(self.StartButton)
        self.StopButton = QtGui.QPushButton(self.SensorTab)
        self.StopButton.setEnabled(False)
        self.StopButton.setObjectName(_fromUtf8("StopButton"))
        self.verticalLayout_5.addWidget(self.StopButton)
        self.SaveButton = QtGui.QPushButton(self.SensorTab)
        self.SaveButton.setEnabled(False)
        self.SaveButton.setObjectName(_fromUtf8("SaveButton"))
        self.verticalLayout_5.addWidget(self.SaveButton)
        self.ResetButton = QtGui.QPushButton(self.SensorTab)
        self.ResetButton.setEnabled(False)
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.verticalLayout_5.addWidget(self.ResetButton)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.TerminalLabel = QtGui.QLabel(self.SensorTab)
        self.TerminalLabel.setObjectName(_fromUtf8("TerminalLabel"))
        self.verticalLayout_7.addWidget(self.TerminalLabel)
        self.TerminalPlainTextEdit = QtGui.QPlainTextEdit(self.SensorTab)
        self.TerminalPlainTextEdit.setReadOnly(True)
        self.TerminalPlainTextEdit.setObjectName(_fromUtf8("TerminalPlainTextEdit"))
        self.verticalLayout_7.addWidget(self.TerminalPlainTextEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.SensorTab, _fromUtf8(""))
        self.FilterTab = QtGui.QWidget()
        self.FilterTab.setObjectName(_fromUtf8("FilterTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.FilterTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.FilterSelectFolderButton = QtGui.QPushButton(self.FilterTab)
        self.FilterSelectFolderButton.setObjectName(_fromUtf8("FilterSelectFolderButton"))
        self.verticalLayout_8.addWidget(self.FilterSelectFolderButton)
        self.FilterFileListWidget = QtGui.QListWidget(self.FilterTab)
        self.FilterFileListWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.FilterFileListWidget.setObjectName(_fromUtf8("FilterFileListWidget"))
        self.verticalLayout_8.addWidget(self.FilterFileListWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.MinCMHLabel = QtGui.QLabel(self.FilterTab)
        self.MinCMHLabel.setObjectName(_fromUtf8("MinCMHLabel"))
        self.gridLayout_5.addWidget(self.MinCMHLabel, 5, 0, 1, 1)
        self.ETLabel = QtGui.QLabel(self.FilterTab)
        self.ETLabel.setObjectName(_fromUtf8("ETLabel"))
        self.gridLayout_5.addWidget(self.ETLabel, 0, 0, 1, 1)
        self.EDateTimeEdit = QtGui.QDateTimeEdit(self.FilterTab)
        self.EDateTimeEdit.setMaximumDate(QtCore.QDate(2037, 12, 31))
        self.EDateTimeEdit.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.EDateTimeEdit.setCalendarPopup(True)
        self.EDateTimeEdit.setObjectName(_fromUtf8("EDateTimeEdit"))
        self.gridLayout_5.addWidget(self.EDateTimeEdit, 0, 1, 1, 1)
        self.LTLabel = QtGui.QLabel(self.FilterTab)
        self.LTLabel.setObjectName(_fromUtf8("LTLabel"))
        self.gridLayout_5.addWidget(self.LTLabel, 1, 0, 1, 1)
        self.LDateTimeEdit = QtGui.QDateTimeEdit(self.FilterTab)
        self.LDateTimeEdit.setDate(QtCore.QDate(2037, 12, 31))
        self.LDateTimeEdit.setTime(QtCore.QTime(23, 59, 59))
        self.LDateTimeEdit.setMaximumDate(QtCore.QDate(2037, 12, 31))
        self.LDateTimeEdit.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.LDateTimeEdit.setCalendarPopup(True)
        self.LDateTimeEdit.setObjectName(_fromUtf8("LDateTimeEdit"))
        self.gridLayout_5.addWidget(self.LDateTimeEdit, 1, 1, 1, 1)
        self.MinTOLabel = QtGui.QLabel(self.FilterTab)
        self.MinTOLabel.setObjectName(_fromUtf8("MinTOLabel"))
        self.gridLayout_5.addWidget(self.MinTOLabel, 2, 0, 1, 1)
        self.MaxTOLabel = QtGui.QLabel(self.FilterTab)
        self.MaxTOLabel.setObjectName(_fromUtf8("MaxTOLabel"))
        self.gridLayout_5.addWidget(self.MaxTOLabel, 3, 0, 1, 1)
        self.MinCMHSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MinCMHSpinBox.setMinimum(0)
        self.MinCMHSpinBox.setMaximum(40)
        self.MinCMHSpinBox.setObjectName(_fromUtf8("MinCMHSpinBox"))
        self.gridLayout_5.addWidget(self.MinCMHSpinBox, 5, 1, 1, 1)
        self.MaxCMHLabel = QtGui.QLabel(self.FilterTab)
        self.MaxCMHLabel.setObjectName(_fromUtf8("MaxCMHLabel"))
        self.gridLayout_5.addWidget(self.MaxCMHLabel, 6, 0, 1, 1)
        self.MaxCMHSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MaxCMHSpinBox.setMinimum(0)
        self.MaxCMHSpinBox.setMaximum(40)
        self.MaxCMHSpinBox.setProperty("value", 40)
        self.MaxCMHSpinBox.setObjectName(_fromUtf8("MaxCMHSpinBox"))
        self.gridLayout_5.addWidget(self.MaxCMHSpinBox, 6, 1, 1, 1)
        self.MinCMLLabel = QtGui.QLabel(self.FilterTab)
        self.MinCMLLabel.setObjectName(_fromUtf8("MinCMLLabel"))
        self.gridLayout_5.addWidget(self.MinCMLLabel, 7, 0, 1, 1)
        self.MinCMLSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MinCMLSpinBox.setMinimum(0)
        self.MinCMLSpinBox.setMaximum(9999)
        self.MinCMLSpinBox.setProperty("value", 0)
        self.MinCMLSpinBox.setObjectName(_fromUtf8("MinCMLSpinBox"))
        self.gridLayout_5.addWidget(self.MinCMLSpinBox, 7, 1, 1, 1)
        self.MaxCMLLabel = QtGui.QLabel(self.FilterTab)
        self.MaxCMLLabel.setObjectName(_fromUtf8("MaxCMLLabel"))
        self.gridLayout_5.addWidget(self.MaxCMLLabel, 8, 0, 1, 1)
        self.MaxCMLSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MaxCMLSpinBox.setMinimum(0)
        self.MaxCMLSpinBox.setMaximum(9999)
        self.MaxCMLSpinBox.setProperty("value", 9999)
        self.MaxCMLSpinBox.setObjectName(_fromUtf8("MaxCMLSpinBox"))
        self.gridLayout_5.addWidget(self.MaxCMLSpinBox, 8, 1, 1, 1)
        self.MinSLabel = QtGui.QLabel(self.FilterTab)
        self.MinSLabel.setObjectName(_fromUtf8("MinSLabel"))
        self.gridLayout_5.addWidget(self.MinSLabel, 9, 0, 1, 1)
        self.MaxSLabel = QtGui.QLabel(self.FilterTab)
        self.MaxSLabel.setObjectName(_fromUtf8("MaxSLabel"))
        self.gridLayout_5.addWidget(self.MaxSLabel, 10, 0, 1, 1)
        self.MinSSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MinSSpinBox.setObjectName(_fromUtf8("MinSSpinBox"))
        self.gridLayout_5.addWidget(self.MinSSpinBox, 9, 1, 1, 1)
        self.MaxSSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MaxSSpinBox.setProperty("value", 99)
        self.MaxSSpinBox.setObjectName(_fromUtf8("MaxSSpinBox"))
        self.gridLayout_5.addWidget(self.MaxSSpinBox, 10, 1, 1, 1)
        self.MinTSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MinTSpinBox.setMaximum(99999)
        self.MinTSpinBox.setObjectName(_fromUtf8("MinTSpinBox"))
        self.gridLayout_5.addWidget(self.MinTSpinBox, 2, 1, 1, 1)
        self.MaxTSpinBox = QtGui.QSpinBox(self.FilterTab)
        self.MaxTSpinBox.setMaximum(99999)
        self.MaxTSpinBox.setProperty("value", 99999)
        self.MaxTSpinBox.setObjectName(_fromUtf8("MaxTSpinBox"))
        self.gridLayout_5.addWidget(self.MaxTSpinBox, 3, 1, 1, 1)
        self.UnitsComboBox = QtGui.QComboBox(self.FilterTab)
        self.UnitsComboBox.setObjectName(_fromUtf8("UnitsComboBox"))
        self.gridLayout_5.addWidget(self.UnitsComboBox, 4, 1, 1, 1)
        self.UnitsLabel = QtGui.QLabel(self.FilterTab)
        self.UnitsLabel.setObjectName(_fromUtf8("UnitsLabel"))
        self.gridLayout_5.addWidget(self.UnitsLabel, 4, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_5)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ShowDataButton = QtGui.QPushButton(self.FilterTab)
        self.ShowDataButton.setEnabled(False)
        self.ShowDataButton.setObjectName(_fromUtf8("ShowDataButton"))
        self.horizontalLayout_4.addWidget(self.ShowDataButton)
        self.SavetoFileButton = QtGui.QPushButton(self.FilterTab)
        self.SavetoFileButton.setEnabled(False)
        self.SavetoFileButton.setObjectName(_fromUtf8("SavetoFileButton"))
        self.horizontalLayout_4.addWidget(self.SavetoFileButton)
        self.SaveFormattedButton = QtGui.QPushButton(self.FilterTab)
        self.SaveFormattedButton.setEnabled(False)
        self.SaveFormattedButton.setObjectName(_fromUtf8("SaveFormattedButton"))
        self.horizontalLayout_4.addWidget(self.SaveFormattedButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.DataPlainTextEdit = QtGui.QPlainTextEdit(self.FilterTab)
        self.DataPlainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.DataPlainTextEdit.setReadOnly(True)
        self.DataPlainTextEdit.setObjectName(_fromUtf8("DataPlainTextEdit"))
        self.verticalLayout_9.addWidget(self.DataPlainTextEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 4)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.FilterTab, _fromUtf8(""))
        self.DataTab = QtGui.QWidget()
        self.DataTab.setObjectName(_fromUtf8("DataTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.DataTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.SelectFolderButton = QtGui.QPushButton(self.DataTab)
        self.SelectFolderButton.setObjectName(_fromUtf8("SelectFolderButton"))
        self.verticalLayout_4.addWidget(self.SelectFolderButton)
        self.GraphFileListWidget = QtGui.QListWidget(self.DataTab)
        self.GraphFileListWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.GraphFileListWidget.setObjectName(_fromUtf8("GraphFileListWidget"))
        self.verticalLayout_4.addWidget(self.GraphFileListWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.DataGraphicsView = PlotWidget(self.DataTab)
        self.DataGraphicsView.setObjectName(_fromUtf8("DataGraphicsView"))
        self.verticalLayout_12.addWidget(self.DataGraphicsView)
        self.GraphSlider = QtGui.QSlider(self.DataTab)
        self.GraphSlider.setEnabled(False)
        self.GraphSlider.setMaximum(24)
        self.GraphSlider.setProperty("value", 12)
        self.GraphSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GraphSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.GraphSlider.setTickInterval(1)
        self.GraphSlider.setObjectName(_fromUtf8("GraphSlider"))
        self.verticalLayout_12.addWidget(self.GraphSlider)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.label_8 = QtGui.QLabel(self.DataTab)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.label_9 = QtGui.QLabel(self.DataTab)
        self.label_9.setIndent(-1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.label_11 = QtGui.QLabel(self.DataTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_10.setStretch(0, 6)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(2, 5)
        self.horizontalLayout_10.setStretch(3, 1)
        self.horizontalLayout_10.setStretch(4, 5)
        self.horizontalLayout_10.setStretch(5, 1)
        self.horizontalLayout_10.setStretch(6, 6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 4)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.DataComboBox = QtGui.QComboBox(self.DataTab)
        self.DataComboBox.setObjectName(_fromUtf8("DataComboBox"))
        self.horizontalLayout_2.addWidget(self.DataComboBox)
        self.DataShowButton = QtGui.QPushButton(self.DataTab)
        self.DataShowButton.setEnabled(False)
        self.DataShowButton.setObjectName(_fromUtf8("DataShowButton"))
        self.horizontalLayout_2.addWidget(self.DataShowButton)
        self.SaveImageButton = QtGui.QPushButton(self.DataTab)
        self.SaveImageButton.setEnabled(False)
        self.SaveImageButton.setObjectName(_fromUtf8("SaveImageButton"))
        self.horizontalLayout_2.addWidget(self.SaveImageButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.DataTab, _fromUtf8(""))
        self.MapTab = QtGui.QWidget()
        self.MapTab.setObjectName(_fromUtf8("MapTab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.MapTab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.MapFolderButton = QtGui.QPushButton(self.MapTab)
        self.MapFolderButton.setObjectName(_fromUtf8("MapFolderButton"))
        self.verticalLayout_10.addWidget(self.MapFolderButton)
        self.MapListWidget = QtGui.QListWidget(self.MapTab)
        self.MapListWidget.setObjectName(_fromUtf8("MapListWidget"))
        self.verticalLayout_10.addWidget(self.MapListWidget)
        self.dirCheckGroupBox = QtGui.QGroupBox(self.MapTab)
        self.dirCheckGroupBox.setObjectName(_fromUtf8("dirCheckGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dirCheckGroupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.nCheck = QtGui.QCheckBox(self.dirCheckGroupBox)
        self.nCheck.setEnabled(False)
        self.nCheck.setMouseTracking(True)
        self.nCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nCheck.setChecked(False)
        self.nCheck.setTristate(True)
        self.nCheck.setObjectName(_fromUtf8("nCheck"))
        self.verticalLayout_6.addWidget(self.nCheck)
        self.eCheck = QtGui.QCheckBox(self.dirCheckGroupBox)
        self.eCheck.setEnabled(False)
        self.eCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.eCheck.setTristate(True)
        self.eCheck.setObjectName(_fromUtf8("eCheck"))
        self.verticalLayout_6.addWidget(self.eCheck)
        self.sCheck = QtGui.QCheckBox(self.dirCheckGroupBox)
        self.sCheck.setEnabled(False)
        self.sCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sCheck.setTristate(True)
        self.sCheck.setObjectName(_fromUtf8("sCheck"))
        self.verticalLayout_6.addWidget(self.sCheck)
        self.wCheck = QtGui.QCheckBox(self.dirCheckGroupBox)
        self.wCheck.setEnabled(False)
        self.wCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.wCheck.setTristate(True)
        self.wCheck.setObjectName(_fromUtf8("wCheck"))
        self.verticalLayout_6.addWidget(self.wCheck)
        self.verticalLayout_10.addWidget(self.dirCheckGroupBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.CompileButton = QtGui.QPushButton(self.MapTab)
        self.CompileButton.setEnabled(False)
        self.CompileButton.setObjectName(_fromUtf8("CompileButton"))
        self.gridLayout_3.addWidget(self.CompileButton, 1, 1, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_2 = QtGui.QLabel(self.MapTab)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.MapTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 1, 2, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.SWnumlabel = QtGui.QLabel(self.MapTab)
        self.SWnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SWnumlabel.setObjectName(_fromUtf8("SWnumlabel"))
        self.gridLayout_12.addWidget(self.SWnumlabel, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem5, 2, 1, 1, 1)
        self.SEnumlabel = QtGui.QLabel(self.MapTab)
        self.SEnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SEnumlabel.setObjectName(_fromUtf8("SEnumlabel"))
        self.gridLayout_12.addWidget(self.SEnumlabel, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.MapTab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem6, 1, 3, 1, 1)
        self.SNnumlabel = QtGui.QLabel(self.MapTab)
        self.SNnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SNnumlabel.setObjectName(_fromUtf8("SNnumlabel"))
        self.gridLayout_12.addWidget(self.SNnumlabel, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_12, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.MapTab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.MapTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 1, 3, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.WNnumlabel = QtGui.QLabel(self.MapTab)
        self.WNnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WNnumlabel.setObjectName(_fromUtf8("WNnumlabel"))
        self.gridLayout_11.addWidget(self.WNnumlabel, 0, 1, 1, 1)
        self.WSnumlabel = QtGui.QLabel(self.MapTab)
        self.WSnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WSnumlabel.setObjectName(_fromUtf8("WSnumlabel"))
        self.gridLayout_11.addWidget(self.WSnumlabel, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.MapTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_11.addWidget(self.label_10, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem8, 3, 1, 1, 1)
        self.WEnumlabel = QtGui.QLabel(self.MapTab)
        self.WEnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WEnumlabel.setObjectName(_fromUtf8("WEnumlabel"))
        self.gridLayout_11.addWidget(self.WEnumlabel, 1, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_11, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.MapTab)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 2, 2, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.NWnumlabel = QtGui.QLabel(self.MapTab)
        self.NWnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NWnumlabel.setObjectName(_fromUtf8("NWnumlabel"))
        self.gridLayout_9.addWidget(self.NWnumlabel, 1, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 1, 0, 1, 1)
        self.NSnumlabel = QtGui.QLabel(self.MapTab)
        self.NSnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NSnumlabel.setObjectName(_fromUtf8("NSnumlabel"))
        self.gridLayout_9.addWidget(self.NSnumlabel, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.MapTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 1, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem10, 0, 2, 1, 1)
        self.NEnumlabel = QtGui.QLabel(self.MapTab)
        self.NEnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NEnumlabel.setObjectName(_fromUtf8("NEnumlabel"))
        self.gridLayout_9.addWidget(self.NEnumlabel, 1, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_18 = QtGui.QLabel(self.MapTab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 2, 1, 1, 1)
        self.ENnumlabel = QtGui.QLabel(self.MapTab)
        self.ENnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ENnumlabel.setObjectName(_fromUtf8("ENnumlabel"))
        self.gridLayout_10.addWidget(self.ENnumlabel, 1, 1, 1, 1)
        self.ESnumlabel = QtGui.QLabel(self.MapTab)
        self.ESnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ESnumlabel.setObjectName(_fromUtf8("ESnumlabel"))
        self.gridLayout_10.addWidget(self.ESnumlabel, 3, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem11, 2, 2, 1, 1)
        self.EWnumlabel = QtGui.QLabel(self.MapTab)
        self.EWnumlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EWnumlabel.setObjectName(_fromUtf8("EWnumlabel"))
        self.gridLayout_10.addWidget(self.EWnumlabel, 2, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem12, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_10, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 3, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.sOutComboBox = QtGui.QComboBox(self.MapTab)
        self.sOutComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.sOutComboBox.setObjectName(_fromUtf8("sOutComboBox"))
        self.horizontalLayout_7.addWidget(self.sOutComboBox)
        self.sInComboBox = QtGui.QComboBox(self.MapTab)
        self.sInComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.sInComboBox.setObjectName(_fromUtf8("sInComboBox"))
        self.horizontalLayout_7.addWidget(self.sInComboBox)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 5, 2, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.nInComboBox = QtGui.QComboBox(self.MapTab)
        self.nInComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.nInComboBox.setObjectName(_fromUtf8("nInComboBox"))
        self.horizontalLayout_8.addWidget(self.nInComboBox)
        self.nOutComboBox = QtGui.QComboBox(self.MapTab)
        self.nOutComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.nOutComboBox.setObjectName(_fromUtf8("nOutComboBox"))
        self.horizontalLayout_8.addWidget(self.nOutComboBox)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 2, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem17)
        self.wOutComboBox = QtGui.QComboBox(self.MapTab)
        self.wOutComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.wOutComboBox.setObjectName(_fromUtf8("wOutComboBox"))
        self.verticalLayout_13.addWidget(self.wOutComboBox)
        self.wInComboBox = QtGui.QComboBox(self.MapTab)
        self.wInComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.wInComboBox.setObjectName(_fromUtf8("wInComboBox"))
        self.verticalLayout_13.addWidget(self.wInComboBox)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem18)
        self.gridLayout_3.addLayout(self.verticalLayout_13, 3, 1, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem19)
        self.eInComboBox = QtGui.QComboBox(self.MapTab)
        self.eInComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.eInComboBox.setObjectName(_fromUtf8("eInComboBox"))
        self.verticalLayout_14.addWidget(self.eInComboBox)
        self.eOutComboBox = QtGui.QComboBox(self.MapTab)
        self.eOutComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.eOutComboBox.setObjectName(_fromUtf8("eOutComboBox"))
        self.verticalLayout_14.addWidget(self.eOutComboBox)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem20)
        self.gridLayout_3.addLayout(self.verticalLayout_14, 3, 3, 1, 1)
        self.MapSaveButton = QtGui.QPushButton(self.MapTab)
        self.MapSaveButton.setEnabled(False)
        self.MapSaveButton.setObjectName(_fromUtf8("MapSaveButton"))
        self.gridLayout_3.addWidget(self.MapSaveButton, 5, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.unknownlabel = QtGui.QLabel(self.MapTab)
        self.unknownlabel.setObjectName(_fromUtf8("unknownlabel"))
        self.horizontalLayout_14.addWidget(self.unknownlabel)
        self.unknownnumlabel = QtGui.QLabel(self.MapTab)
        self.unknownnumlabel.setObjectName(_fromUtf8("unknownnumlabel"))
        self.horizontalLayout_14.addWidget(self.unknownnumlabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 1, 3, 1, 1)
        self.ClearButton = QtGui.QPushButton(self.MapTab)
        self.ClearButton.setObjectName(_fromUtf8("ClearButton"))
        self.gridLayout_3.addWidget(self.ClearButton, 5, 3, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_3)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.MapTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSerial_Connection = QtGui.QAction(MainWindow)
        self.actionSerial_Connection.setObjectName(_fromUtf8("actionSerial_Connection"))
        self.actionBLE_Connection = QtGui.QAction(MainWindow)
        self.actionBLE_Connection.setObjectName(_fromUtf8("actionBLE_Connection"))
        self.actionDownload = QtGui.QAction(MainWindow)
        self.actionDownload.setObjectName(_fromUtf8("actionDownload"))
        self.actionUpload = QtGui.QAction(MainWindow)
        self.actionUpload.setObjectName(_fromUtf8("actionUpload"))
        self.actionSet_Up = QtGui.QAction(MainWindow)
        self.actionSet_Up.setObjectName(_fromUtf8("actionSet_Up"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RCDS Tool", None))
        self.SensorGroupBox.setTitle(_translate("MainWindow", "Sensor Connection", None))
        self.SerialRadioButton.setText(_translate("MainWindow", "Serial USB", None))
        self.BLERadioButton.setText(_translate("MainWindow", "Bluetooth", None))
        self.ScanDevicesButton.setText(_translate("MainWindow", "Scan Devices", None))
        self.DeviceConnectButton.setText(_translate("MainWindow", "Connect", None))
        self.IDLabel.setText(_translate("MainWindow", "ID", None))
        self.LocLabel.setText(_translate("MainWindow", "Location", None))
        self.DirLabel.setText(_translate("MainWindow", "Direction", None))
        self.CommentLabel.setText(_translate("MainWindow", "Comment", None))
        self.StateLabel.setText(_translate("MainWindow", "State", None))
        self.SetButton.setText(_translate("MainWindow", "Set Parameters", None))
        self.StartButton.setText(_translate("MainWindow", "Start Running", None))
        self.StopButton.setText(_translate("MainWindow", "Stop Running", None))
        self.SaveButton.setText(_translate("MainWindow", "Save Data", None))
        self.ResetButton.setText(_translate("MainWindow", "Reset Device", None))
        self.TerminalLabel.setText(_translate("MainWindow", "Terminal", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SensorTab), _translate("MainWindow", "Sensor Control", None))
        self.FilterSelectFolderButton.setText(_translate("MainWindow", "Select Folder", None))
        self.MinCMHLabel.setText(_translate("MainWindow", "Min Car Height (cm)", None))
        self.ETLabel.setText(_translate("MainWindow", "Earliest Data", None))
        self.LTLabel.setText(_translate("MainWindow", "Latest Data", None))
        self.MinTOLabel.setText(_translate("MainWindow", "Min Milliseconds", None))
        self.MaxTOLabel.setText(_translate("MainWindow", "Max Milliseconds", None))
        self.MaxCMHLabel.setText(_translate("MainWindow", "Max Car Height (cm)", None))
        self.MinCMLLabel.setText(_translate("MainWindow", "Min Car Length (cm)", None))
        self.MaxCMLLabel.setText(_translate("MainWindow", "Max Car Length (cm)", None))
        self.MinSLabel.setText(_translate("MainWindow", "Min Speed (kmh)", None))
        self.MaxSLabel.setText(_translate("MainWindow", "Max Speed (kmh)", None))
        self.UnitsLabel.setText(_translate("MainWindow", "Units (Imperial/SI)", None))
        self.ShowDataButton.setText(_translate("MainWindow", "Show Data", None))
        self.SavetoFileButton.setText(_translate("MainWindow", "Save to File", None))
        self.SaveFormattedButton.setText(_translate("MainWindow", "Save Formatted", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FilterTab), _translate("MainWindow", "Filtering and Compilation", None))
        self.SelectFolderButton.setText(_translate("MainWindow", "Select Folder", None))
        self.label_8.setText(_translate("MainWindow", "06h", None))
        self.label_9.setText(_translate("MainWindow", "12h", None))
        self.label_11.setText(_translate("MainWindow", "18h", None))
        self.DataShowButton.setText(_translate("MainWindow", "Show Data", None))
        self.SaveImageButton.setText(_translate("MainWindow", "Save Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataTab), _translate("MainWindow", "Data Visualization", None))
        self.MapFolderButton.setText(_translate("MainWindow", "Select Folder", None))
        self.dirCheckGroupBox.setTitle(_translate("MainWindow", "Active Devices", None))
        self.nCheck.setText(_translate("MainWindow", "North", None))
        self.eCheck.setText(_translate("MainWindow", "East", None))
        self.sCheck.setText(_translate("MainWindow", "South", None))
        self.wCheck.setText(_translate("MainWindow", "West", None))
        self.CompileButton.setText(_translate("MainWindow", "Compile Data", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/intersection_top.png\"/></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/intersection_center.png\"/></p></body></html>", None))
        self.SWnumlabel.setText(_translate("MainWindow", "0", None))
        self.SEnumlabel.setText(_translate("MainWindow", "0", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/arrowSouth.jpg\"/></p></body></html>", None))
        self.SNnumlabel.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/intersection_left.png\"/></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/intersection_right.png\"/></p></body></html>", None))
        self.WNnumlabel.setText(_translate("MainWindow", "0", None))
        self.WSnumlabel.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/arrowWest.jpg\"/></p></body></html>", None))
        self.WEnumlabel.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/intersection_bottom.png\"/></p><p><br/></p></body></html>", None))
        self.NWnumlabel.setText(_translate("MainWindow", "0", None))
        self.NSnumlabel.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/arrowNorth.jpg\"/></p></body></html>", None))
        self.NEnumlabel.setText(_translate("MainWindow", "0", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/intersection/arrowEast.jpg\"/></p></body></html>", None))
        self.ENnumlabel.setText(_translate("MainWindow", "0", None))
        self.ESnumlabel.setText(_translate("MainWindow", "0", None))
        self.EWnumlabel.setText(_translate("MainWindow", "0", None))
        self.MapSaveButton.setText(_translate("MainWindow", "Save Order Data", None))
        self.unknownlabel.setText(_translate("MainWindow", "Unknown:", None))
        self.unknownnumlabel.setText(_translate("MainWindow", "0", None))
        self.ClearButton.setText(_translate("MainWindow", "Clear Devices", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MapTab), _translate("MainWindow", "Map Layout", None))
        self.actionSerial_Connection.setText(_translate("MainWindow", "Serial Connection", None))
        self.actionBLE_Connection.setText(_translate("MainWindow", "BLE Connection", None))
        self.actionDownload.setText(_translate("MainWindow", "Download", None))
        self.actionUpload.setText(_translate("MainWindow", "Upload", None))
        self.actionSet_Up.setText(_translate("MainWindow", "Set Up", None))

from pyqtgraph import PlotWidget
import rcds_res_rc
